### ISSUE TITLE
Support for CocosStudio?

### ISSUE THREAD

**Issue by darmie** [Cocos2DXNA/cocos2d-xna#472] opened 2015-05-05 15:07 UTC
Hi, I would like to use this framework for Windows Phone 8 development, I couldn't find any test code for Cocos Studio extension in Cocos2d-xna. Would this feature be supported? When would it be supported?

**Comment by totallyeviljake** [comment] 2015-05-05 22:08
Cocos Studio can write out the CBI format, which is the old cocos2d-x v2 "cocos builder" format. 

The new cocos2d v3 extensions are not supported in cocos2d-xna. Therefore any direct support for cocos studio will require supporting the v3 changes, which we have started working on, but we are not ready for any release yet.

**Comment by totallyeviljake** [comment] 2015-05-05 22:15
This is a duplicate of #444

**Closed by totallyeviljake** 2015-05-05 22:15 UTC

**Comment by darmie** [comment] 2015-05-06 08:58
OK thank you. I'll anticipate a release.
